language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_binary_packages:
    - BBmisc
    - checkmate
    - brew
    - digest
    - DBI
    - RSQLite
    - stringi
    - testthat

r_github_packages:
    - jimhester/covr
    - mllg/fail
    - rstats-db/RSQLite

after_success:
    - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
